name: checkOV PR Scan

on:
  pull_request:
    branches: [ main ]  # PR 대상 브랜치

jobs:
  run-checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # PR 브랜치 체크아웃

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: |
          checkov -d . > result.txt || true
          if grep -q "Critical" result.txt; then
            echo "CRITICAL_FOUND=true" >> $GITHUB_ENV
          fi

      - name: Create critical flag file if needed
        if: env.CRITICAL_FOUND == 'true'
        run: |
          mkdir -p .github/flags
          echo "⚠️ Critical issue found by Checkov" > .github/flags/critical.txt
      
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/flags/critical.txt
      
          # 파일에 변경이 생긴 경우에만 커밋 & 푸시
          if ! git diff --cached --quiet; then
            git commit -m "chore: add critical flag due to Checkov result"
            git push
          else
            echo "✅ No changes to commit. Skipping push."
          fi
