name: ben-test
on:
  issue_comment:
    types: [created]

jobs:
  test:
    name: test
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/terraform') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.0.0"

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color > plan.txt
        working-directory: cand8
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Plan Output
        id: get_plan
        run: |
          echo "PLAN<<EOF" >> $GITHUB_ENV
          cat cand8/plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan Results
            \`\`\`
            ${process.env.PLAN}
            \`\`\`
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
    